language: go

go:
- 1.8

dist: trusty

sudo: required

before_install:
- sudo apt-get update
- sudo apt-get install -y pkg-config wget automake libtool make

before_script:
- wget https://dist.libuv.org/dist/v1.14.1/libuv-v1.14.1.tar.gz
- tar xzf libuv-v1.14.1.tar.gz
- cd libuv-v1.14.1
- sh autogen.sh
- ./configure
- make
- sudo make install
- sudo ldconfig
- cd ..
- go get github.com/mattn/goveralls

script: go test -v ./... && $HOME/gopath/bin/goveralls -service=travis-ci