language: go

go:
- 1.8
- 1.9

sudo: enabled

before_script:
- sudo apt-get -qq update
- sudo apt-get install -y pkg-config wget automake libtool make
- wget https://dist.libuv.org/dist/v1.14.1/libuv-v1.14.1.tar.gz
- tar xzf libuv-v1.14.1.tar.gz
- cd libuv-v1.14.1
- sh autogen.sh
- ./configure
- make
- sudo make install
- sudo ldconfig

script: go test -v ./... && $HOME/gopath/bin/goveralls -service=travis-ci